### ISSUE TITLE
Generated PY file not found

### ISSUE THREAD

**Issue by u-Aymane** [kensh1ro/camouflage#2]
![image](https://user-images.githubusercontent.com/101131248/176520871-9d94e3f9-5e4a-46ad-a6f4-04f0652a54d1.png)

Solution is you have to copy the last commit you did, and modify line 198

```python
try:
    banner = "\n\t\t\t𝕮𝖆𝖒𝖔𝖚𝖋𝖑𝖆𝖌𝖊 ρутнση мєтєяρяєтєя ¢яуρтєя\n"
    print(banner)
except:
    pass
```

I think while trying to fix it you removed some lines

and it works

![image](https://user-images.githubusercontent.com/101131248/176521234-da4a362a-61af-4d9c-9418-9d4f33bfc3a9.png)

**Comment by kensh1ro** [comment]
Could you elaborate more please? Share the output

**Comment by u-Aymane** [comment]
I did fix the script by just adding try except to commit before the last one, the last commit has some issues
