### ISSUE TITLE
Error in developing program

### ISSUE THREAD

**Issue by marik22354** [kensh1ro/camouflage#4]
Script tries to write a temporary file in folder "output", but then it says that file doesn't exist (and ofc I'm on Windows 10 H20)

camouflage.py -p tcp -H 192.168.1.9:8888 --packer compile -o Final --icon icon.ico

Nuitka-Options:INFO: Used command line options: --windows-company-name=Obsidian --windows-product-name=Obsidian --windows-file-version=0.14.0.6 --windows-product-version=0.14.0.6 --windows-file-description=Obsidian --onefile --windows-disable-console --remove-output --assume-yes-for-downloads temp/icZMEmBlAMs.py -o output/Final.exe --windows-icon-from-ico=icon.ico
FATAL: Error, file 'temp/icZMEmBlAMs.py' is not found.
[+] Done creating final executable "output/Final.exe"

The point is that the temporary file is created, but the script ignore it and throw error. I tried also to create manually a folder called "temp" to fix the error, but it doesn't work. (I admit I'm not good at programming) If you can fix that it would to be approeciated

**Comment by kensh1ro** [comment]
Alright, I will look into it

**Comment by kensh1ro** [comment]
the issue was fixed, it turns out python was searching for .py file instead of .pyw.
